name: Deploy docs

on:
  push:
    branches: [ master, docs_fix ]

jobs:
  deploy-docs:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          sudo apt-get install pandoc
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
      - name: Build the docs
        run: tools/build_docs.sh
      - name: Push documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/build/_html
          publish_branch: gh-pages
          deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
